export const environment = {
  production: true,
  useMock: false,
  apiUrl: '/api',
  authUrl: '/api/auth',
  flightUrl: '/api/flights',
  inventoryUrl: '/api/inventory',
  reservationUrl: '/api/reservations',
  paymentUrl: '/api/payments',
  ticketingUrl: '/api/tickets',
  checkinUrl: '/api/checkin',
  baggageUrl: '/api/baggage',
  loyaltyUrl: '/api/loyalty',
  operationsUrl: '/api/operations',
  adminUrl: '/api/admin',
};
